Update windows_tensorrt-rtx.yml

diff --git a/.github/workflows/windows_tensorrt-rtx.yml b/.github/workflows/windows_tensorrt-rtx.yml
--- a/.github/workflows/windows_tensorrt-rtx.yml
+++ b/.github/workflows/windows_tensorrt-rtx.yml
@@ -73,3 +73,142 @@ jobs:
       run: |
         echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9" >> $env:GITHUB_ENV
         echo "CUDA_PATH_V12_9=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9" >> $env:GITHUB_ENV
+
+#    - name: Cache cuDNN
+#      id: cache-cudnn
+#      uses: actions/cache@v5
+#      with:
+#        path: "C:\\Program Files\\NVIDIA\\CUDNN\\v9.19"
+#        key: CUDNN_V9_19
+#    - name: Download cuDNN
+#      if: steps.cache-cudnn.outputs.cache-hit != 'true'
+#      run: |
+#        curl --ssl-revoke-best-effort -L "https://developer.download.nvidia.com/compute/cudnn/9.19.1/local_installers/cudnn_9.19.1_windows_x86_64.exe" -o "cuDNN.exe"
+#    - name: Install cuDNN
+#      if: steps.cache-cudnn.outputs.cache-hit != 'true'
+#      run: |
+#        Start-Process -Wait "cuDNN.exe" -ArgumentList "-s"
+# NOTE: STORING CACHE REQUIRES THE RUN TO SUCCEED, SO IF IT'S FAILING, TRY TEMPORARILY REMOVING ALL THE STEPS BELOW THIS LINE
+
+#    - name: Install vcpkg
+#      uses: lukka/run-vcpkg@v11.5
+#      with:
+#        vcpkgGitCommitId: c2aeddd80357b17592e59ad965d2adf65a19b22f
+#    - name: Install dependencies
+#      run: |
+#        vcpkg install 
+
+    - name: Print PATH A
+      run: |
+        echo $Env:Path
+        echo ${{env.PATH}}
+
+    - name: Download Dependencies
+      run: |
+        curl --ssl-revoke-best-effort --create-dirs -L "https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/1.1/TensorRT-RTX-1.1.1.26.Windows.win10.cuda-12.9.zip" -o "TensorRT-RTX.zip"
+        7z x "TensorRT-RTX.zip"
+        $Env:Path = "${{github.workspace}}\TensorRT-RTX\TensorRT-RTX-1.1.1.26\lib;" + $Env:Path
+
+    - name: Print PATH B
+      run: |
+        echo $Env:Path
+        echo ${{env.PATH}}
+
+    - name: List files
+      run: ls -R
+
+    - name: Build
+      run: >
+        .\build.bat
+        --config Release
+        --build_dir build
+        --parallel
+        --use_nv_tensorrt_rtx
+        --tensorrt_rtx_home "${{github.workspace}}\TensorRT-RTX\TensorRT-RTX-1.1.1.26"
+        --cuda_home "${{env.CUDA_PATH}}"
+        --cmake_generator "Visual Studio 17 2022"
+        --build_shared_lib
+        --skip_tests
+        --build
+        --update
+        --use_vcpkg        
+
+    - name: List files
+      run: ls -R
+
+#    - name: Deploy
+#      shell: cmd
+#      run: |
+#        windeployqt.exe "${{github.workspace}}/${{env.Artifacts}}/${{env.Executable}}"
+#        If exist "vcpkg\installed\${{matrix.Settings.Platform}}-windows\bin\*.dll"       (copy "vcpkg\installed\${{matrix.Settings.Platform}}-windows\bin\*.dll"       "${{env.Artifacts}}")
+#        If exist "vcpkg_installed\${{matrix.Settings.Platform}}-windows\bin\*.dll"       (copy "vcpkg_installed\${{matrix.Settings.Platform}}-windows\bin\*.dll"       "${{env.Artifacts}}")
+#        If exist "vcpkg\installed\${{matrix.Settings.Platform}}-windows\debug\bin\*.dll" (copy "vcpkg\installed\${{matrix.Settings.Platform}}-windows\debug\bin\*.dll" "${{env.Artifacts}}")
+#        If exist "vcpkg_installed\${{matrix.Settings.Platform}}-windows\debug\bin\*.dll" (copy "vcpkg_installed\${{matrix.Settings.Platform}}-windows\debug\bin\*.dll" "${{env.Artifacts}}")
+#        xcopy "assets\" "${{env.Artifacts}}\assets\" /s
+
+    - name: Upload artifacts
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{env.Title}}-${{matrix.Settings.Name}}-${{matrix.Configuration}}
+        path: "${{github.workspace}}/${{env.Artifacts}}/"
+
+  Release:
+    name: Release
+    runs-on: windows-latest
+    needs: Build
+    steps:
+
+      - name: Clone repo and submodules
+        run: git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git "${{github.workspace}}" --branch ${{env.Branch}} --recurse-submodules
+
+      - name: Get current date, commit hash and count
+        run: |
+          echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
+          echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
+          echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
+          echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
+          echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV
+
+#      - name: Download Artifacts - Win32
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: ${{env.Title}}-Win32-Release
+#          path: Release/Win32/
+
+      - name: Download Artifacts - Win64
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{env.Title}}-Win64-Release
+          path: Release/Win64/
+
+      - name: Deploy
+        run: |
+          cp "README.md" "Release/ReadMe.txt"
+          cp "LICENSE" "Release/License.txt"
+  
+      - name: Compress artifacts
+        if: github.event_name == 'push'
+        run: |
+          7z a "Release/${{env.Title}}.zip" "${{github.workspace}}/Release/*" -mx=9
+          cp "Release/${{env.Title}}.zip" "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"
+  
+      - name: Purge tag - latest-${{env.Branch}}
+        if: github.event_name == 'push'
+        run: |
+          gh release delete latest-${{env.Branch}} --repo ${{github.repository}} --cleanup-tag --yes || true
+  
+      - name: Release - archive-${{env.Branch}}
+        if: github.event_name == 'push'
+        run: |
+          gh release create archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
+          Build logs: https://github.com/${{github.repository}}/actions" || true
+          gh release edit archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
+          Build logs: https://github.com/${{github.repository}}/actions" || true
+          gh release upload archive-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"
+  
+      - name: Release - latest-${{env.Branch}}
+        if: github.event_name == 'push'
+        run: |
+          gh release create latest-${{env.Branch}} --repo ${{github.repository}} --target ${{env.CommitHash}} --generate-notes --latest=true --title "${{env.Title}} r${{env.CommitCount}}@${{env.CommitHashShort}}" --notes "Build archive: https://github.com/${{github.repository}}/releases/tag/archive-${{env.Branch}}
+          Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
+          gh release upload latest-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}.zip"
